### PR TITLE
Fixes #379

### LINKED ISSUE #379: Incorrect handling of -c option with %
The following code does not expect `%` in the beginning of `-c` option and fails on "Wrong number syntax": 

https://github.com/tabulapdf/tabula-java/blob/ebc83ac2bb1a1cbe54ab8081d70f3c9fe81886ea/src/main/java/technology/tabula/CommandLineApp.java#L59-L61

That piece of code is not needed at all because `-c` option is already parsed in this piece of code that was already ran:
https://github.com/tabulapdf/tabula-java/blob/ebc83ac2bb1a1cbe54ab8081d70f3c9fe81886ea/src/main/java/technology/tabula/CommandLineApp.java#L54

### PR DESCRIPTION
**Pull request by Milchreis**
Removes the incorrect double handling of -c option mentioned in #379

### CODE REVIEW

File: src/main/java/technology/tabula/CommandLineApp.java [hunk 1]
```diff
@@ -290,7 +285,15 @@ private static TableExtractor createExtractor(CommandLine line) throws ParseExce
         List<Float> rv = new ArrayList<>();
         try {
             for (int i = 0; i < f.length; i++) {
-                rv.add(Float.parseFloat(f[i]));
+                final String element = f[i];
+
+                if (element.startsWith("%")) {
+
+                    rv.add(Float.parseFloat(element));
```
Comment (jazzido) [inline src/main/java/technology/tabula/CommandLineApp.java:292]: Why both branches execute the same code?

**Review by jazzido — CHANGES_REQUESTED** [review]
Hey, thanks! I left a question :)

File: src/main/java/technology/tabula/CommandLineApp.java (hunk 1 above)
Comment (Milchreis) [reply src/main/java/technology/tabula/CommandLineApp.java]: You are right. Sorry, I didn't want left this code behind in that way. It was by accident.
